server:
  port: 8086
spring:
  application:
    name: GATE-WAY
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: Welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet          